In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')


In [3]:
df.sample(5)

age  gender   review education purchased
0    30  Female  Average    School        No
35   74    Male     Poor    School       Yes
23   96  Female     Good    School        No
33   89  Female     Good        PG       Yes
8    65  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [11]:
df.head(10)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No
5  Average    School       Yes
6     Good    School        No
7     Poor    School       Yes
8  Average        UG        No
9     Good        UG       Yes

In [16]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
encoder = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
encoder.fit_transform(df.drop('purchased',axis=1))



array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [19]:
encoder.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [80]:
from sklearn.preprocessing import OrdinalEncoder

In [81]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(['purchased'],axis=1),df['purchased'],test_size=0.2,random_state=42)

In [82]:
X_train

review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [83]:
encoder = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
encoder.fit(X_train)
print(encoder.categories_)

transformed_X = encoder.transform(X_train)
print(transformed_X)

[array(['Poor', 'Average', 'Good'], dtype=object), array(['School', 'UG', 'PG'], dtype=object)]
[[0. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [2. 2.]
 [2. 0.]
 [2. 2.]
 [0. 2.]
 [2. 2.]
 [0. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 2.]
 [2. 2.]
 [1. 0.]
 [1. 1.]
 [2. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]
 [2. 0.]
 [2. 1.]
 [0. 2.]
 [2. 0.]
 [2. 1.]
 [1. 0.]
 [0. 0.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]]


In [43]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=42)

In [8]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [91]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [92]:
X_train = oe.transform(X_train)

In [93]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.]])

In [86]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [87]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le = LabelEncoder()

In [97]:
le.fit(y_train)

LabelEncoder()

In [98]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [99]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [100]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])